### ISSUE TITLE
White areas in Progress tab

### ISSUE THREAD

**Issue by rohitgehe05** [joeynotjoe/Asana-Darkness#1]
## Issue
There is a whitespace under the area graph in the progress tab of a project

## Screenshot
![image](https://user-images.githubusercontent.com/18504667/80282819-2446fa00-8731-11ea-91be-f204e1e12eaf.png)

**Comment by joeynotjoe** [comment]
@rohitgehe05 I think this is fixed? Let me know if you still see issues.
