### ISSUE TITLE
White areas in Form tab

### ISSUE THREAD

**Issue by rohitgehe05** [joeynotjoe/Asana-Darkness#2]
## Issue
When creating a form, there are white areas in specific form elements such as long answer and file attachment

## Screenshot
![image](https://user-images.githubusercontent.com/18504667/80282871-738d2a80-8731-11ea-8750-628a3ac17394.png)

**Comment by joeynotjoe** [comment]
I think I have most of these taken care of. You are discovering all of the areas of Asana that I don't personally use @rohitgehe05, lol!

**Comment by joeynotjoe** [comment]
@rohitgehe05 - should be fixed and merged to master. :) Let me know if you have any more trouble!

**Comment by rohitgehe05** [comment]
@joeynotjoe - is this also updated on https://userstyles.org/styles/150563/asana-darkness -- I'm currently using the Stylish chrome extension?
Thanks 🙏
